liip_imagine:
  driver: gd
  # resolvers :
  #     default :
  #         web_path : ~

  filter_sets:
    #use the default cache configuration
    #cache : ~
    my_thumb:
      quality: 75
      filters:
        thumbnail: { size: [ 70, 50 ], mode: outbound, allow_upscale: true }
    #        thumbnail: { size: [ 260, 130 ], position: center, color: '#157347' , mode: outbound, allow_upscale: true }
    medium:
      quality: 75
      filters:
        thumbnail: { size: [ 460, 230 ], mode: outbound, allow_upscale: true }

    large:
      quality: 75
      filters:
        thumbnail: { size: [ 700, 430 ], mode: outbound, allow_upscale: true }

    small:
      quality: 75
      filters:
        thumbnail: { size: [ 230, 130 ], mode: outbound, allow_upscale: true }
