security:
  enable_authenticator_manager: true
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    App\Entity\User:
      algorithm: auto
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      custom_authenticator: App\Security\LoginFormAuthenticator
#      json_login:
#        check_path: api_platform_login
#        username_path: username
#        password_path: password
      logout:
        path: /logout
      user_checker: App\Security\UserChecker
      access_denied_url: access_denied
      #        target: home
  access_control:
#    - { path: ^/login$, roles: IS_ANONYMOUS }
#    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/root/admin, roles: ROLE_ADMIN }
#    - { path: ^/root/admin/users, roles: ROLE_ADMIN }

